name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Apk
      run: ./gradlew assembleRelease
      
    - name: Upload Release Build to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: |
           app/build/outputs/apk/release/
    - name: Create Github Release
      uses: softprops/action-gh-release@v1
      with:
         generate_release_notes: true
         prerelease: true
         tag: Github-rels
         files: |
           app/build/outputs/apk/release/app-release.apk
